### ISSUE TITLE
Stakeholder vs Citizen Engagement: Seeking References & Case Studies

### ISSUE THREAD

**Issue by laurawesley** [canada-ca/welcome#16]
Recently a number of people have shared articles, posts and case studies about various experiences working with stakeholders and citizens, or including people who wouldn't normally be involved in public consultations. Does anyone know of more like this?

http://www.publicdeliberation.net/cgi/viewcontent.cgi?article=1250&context=jpd

http://csdc-cecd.ca/blog/2017/01/06/speaker-series-david-farrell/

https://nextcity.org/daily/entry/seattles-community-planning-experiment-fell-short

**Comment by ThomKearney** [comment]
Thanks for sharing those Laura, very interesting reading. 
I will keep a look out for similar things.

**Comment by patcon** [comment]
Thanks @laurawesley! I know this was dropped elsewhere, but just so it's in the same place:
https://blog.pol.is/uber-responds-to-vtaiwans-coherent-blended-volition-3e9b75102b9b#.2knrbw7dp

**Comment by thebestsophist** [comment]
The Democratic Progressive Party has been working on deliberative practices since they gained control of Taiwanese government the first time in 2000. One of their first attempts was for reforming Taiwan’s national health insurance, [this piece in the December 2013 issue of the Taiwan Journal of Democracy](http://www.tfd.org.tw/export/sites/tfd/files/publication/journal/dj0902/004.pdf) (pdf, sorry) covers a good bit of what Taiwan has worked on before vTaiwan.

I don’t remember if it was covered in that piece in particular, but I thin it’s super important to note that vTaiwan is only the latest iteration of deliberative practices that also grew in local city and neighborhood planning for them.

**Comment by MaryBethBaker** [comment]
Archiving this issue. Case studies for the GC have been posted on gcwiki: https://wiki.gccollab.ca/Public_Engagement_Case_Studies
