### ISSUE TITLE
Consultation Data Standards / Normes de données des consultations

### ISSUE THREAD

**Issue by robobotman** [canada-ca/welcome#19]
(cc: @MaryBethBaker @jpmckinney @howardttam)

We are wondering if it’s possible to create a data store of feedback from public consultations across government and the public engagement domain. Consultations take place in Canada on public policy and regulations within many specific domains from health care to the environment. 

Has anyone experimented with potential consultation data standards (at any level) to enable data sharing protocols to help improve access? 

We think consultation data should be considered a resource for public consumption and available for‎ re-use for future projects, programs, research, consultations or other activities toward better public policy and results. 

Here are two examples of consultation datasets available at open.canada.ca. 
http://open.canada.ca/data/en/dataset/74aa0e1a-8e13-4ddb-a31e-129c253a09b3
http://open.canada.ca/data/en/dataset/5e9433bf-2334-463a-bd48-03ba53a7051c

---------------

Nous nous demandons s’il est possible de créer un répertoire des commentaires reçus par suite des consultations publiques menées par le gouvernement dans son ensemble et dans le domaine de la mobilisation publique. Des consultations sont menées au Canada au sujet de politiques publiques et de règlements portant sur des enjeux spécifiques, qu’il s’agisse de soins de santé ou d’environnement, entre autres.

Quelqu’un a-t-il déjà mis à l’essai des mesures de normalisation de données relatives aux consultations (peu importe le niveau) afin d’établir des protocoles pour le partage de données et un accès plus facile?

Nous sommes d’avis que les données des consultations doivent être considérées comme une ressource publique qui peut être réutilisée pour d’éventuels projets, programmes, recherches, consultations ou autres activités en vue d’obtenir de meilleures politiques publiques et de meilleurs résultats.

Voici deux exemples de bases de données relatives à des consultations, lesquelles sont accessibles par l’entremise de ouvert.canada.ca.
http://open.canada.ca/data/en/dataset/74aa0e1a-8e13-4ddb-a31e-129c253a09b3
http://open.canada.ca/data/en/dataset/5e9433bf-2334-463a-bd48-03ba53a7051c

**Comment by patcon** [comment]
cc: @biancawylie

**Comment by jpmckinney** [comment]
I'm not sure what the use cases are for standardization. There's high variability in the data collected by consultations. Just for the case of consultations that use a questionnaire, there is a lot of variability across questions (multiple choice, free text, etc.). Demographic questions would require mapping the possible answers to code lists, and in some cases can't be mapped to a standard (for example, some questionnaires ask for a specific age, others have different kinds of age ranges).

Considering the variance, users of the data will still need to do a lot of hard work before they can do any aggregate analysis across multiple consultations, I think.

**Comment by robotbotman** [comment]
You’re absolutely right. Data at the lowest level would be next impossible to standardize. But maybe it would be possible according to a consultation classification? Or how about at the discovery level? Something incredibly simple to facilitate cross-x sharing to support a culture of continues engagement. Could that be one use case? 

There’s movement toward being able to measure the performance of citizen engagement in Canada. To support such analyses, it would great if we can comb data with basic standard tags – to start. Maybe geolocation data?

**Comment by jpmckinney** [comment]
For discovering consultations, I think a feed (whether in iCal, Atom/RSS, etc.) would satisfy the simple use cases. Consulting Canadians has a lot of consultations, many of which are for a narrow niche: http://www1.canada.ca/consultingcanadians/ A step-up from a basic feed would add some fields to help people filter the consultation opportunities.

For the use case of comparing performance, the easiest things to measure and standardize are numbers of participants, contributions, etc. But the real performance of a consultation, I think, has to do with policy formation, consensus building, buy-in, etc. Those are more frequently measured using a post-consultation survey, but then we fall into the same standardization challenges as raised earlier.

**Comment by patcon** [comment]
Based on previous conversations, I feel like @howardttam might have thoughts here. He brought up that many comments in consultations are deemed "out of scope" of the question being asked, but if they were kept around and made more available to later consultations professionals (and perhaps marked as unactionable), then they wouldn't be so "wasted". And citizens might actually start feeling like these consultations weren't so atomic and disconnected, but perhaps linked, so that participants time felt more valued.

I'm not sure I'm doing the concern justice, so perhaps howard could step up :)

Also, perhaps a standard isn't the right approach. But the feedback and data is very messy at the moment, in my understanding

**Comment by MaryBethBaker** [comment]
Thanks for the analysis @jpmckinney. We've been thinking about what open and transparent government consultations look like with regard to Open data and I agree with you we need use cases before we move forward. 

For more context, we've been thinking about...
What if we had minimum data required for particular consultations methods/based within a specific the domain (i.e. Environment, health or regulations)? I know @howardttam was working on poverty or homelessness. I can see the use cases for Open Government consultation data standards across jurisdictions. But I'm just exploring this idea with @robobotman at the moment so we'll take into account these comments, especially discoverability of consultations. We also have the use case of subscribe to specific consultation themes.

**Comment by MaryBethBaker** [comment]
Also noting the post-consultation survey suggestion. Thanks @jpmckinney.

// @robobotman

**Comment by MaryBethBaker** [comment]
Has anyone in this thread taken a look at the repo for https://github.com/bcgov/openconsult? I just heard about it and am going to reach out to BC to see what they've learned through their work.

//  @robobotman @jpmckinney @patcon @howardttam

**Comment by patcon** [comment]
> We've been thinking about what open and transparent government consultations look like with regard to Open data

Related: city staff in Toronto's CIO office (specifically @deniscarr, working with [Lan Nguyen](https://www.linkedin.com/in/lanphnguyen) and [Jessica Rayes](https://www.linkedin.com/in/jessicarayes)) are interested in doing a non-conventional consultation in preparation for writing the Open Data Strategic Plan that City Council has requested from them. They are very genuine about writing the report in collaboration with the community and other stakeholders, which is apparently very unconventional for staff reports.

There is a lot of excitement around taking cues from the vTaiwan process.

Further, there is talk of doing a "meta" consultation to help inform _how_ the open data consult will run. I believe this is on the table because many [Civic Tech Toronto](civictech.ca) members are excited about the consultation process itself, almost as much as open data :)

So regardless, this will likely result in lots of conversation about consultations and open data in Toronto in the next few months ;)

**Comment by jpmckinney** [comment]
@MaryBethBaker I've read OpenConsult quickly, and I don't see how much it adds over simply creating events in a calendar and then sharing those events via iCal (or other). (iCal is an IETF standard by the way.) Most of OpenConsult's CSV column names have the same semantics as existing iCal fields. Given the types of data that OpenConsult covers, the most natural thing is to load the data into a calendar.

With OpenConsult, a publisher would create the data file using spreadsheet software and export it as CSV. The publisher would have to regularly republish the data file. Users would then need to read that data into a system before it's at all useful.

With iCal, a publisher can create events using calendar software and export it as iCal. Most calendar software already has the functionality to continuously publish an iCal feed to the world, so there is no extra step to republish the data. Users can immediately use the data by clicking an iCal link in their browser, which their calendar software will open (or they can copy the link and manually add it to their calendar). That's because iCal is already a very broadly adopted standard.

On balance it seems to me that simply making effective use of iCal satisfies the same use cases and takes advantage of iCal's broad implementation, which gives non-technical users greater access to this information and makes it immediately useful without any transformation or processing required.

**Comment by biancawylie** [comment]
A lot of what James said here rings true to me around the challenges with standardization of large sets of qualitative consultation data. And so much gets lumped into the "other thoughts?" open ended kind of questions. 

I'm thinking about the minimum data/theme idea. For Environment, for example, this would be like including which type of EA it is (for the federal case, responsible authority or review panel)? For some cases I can see where this might help someone quickly select which consultations they want to consider for their analysis. Perhaps another point would be to standardize the inclusion of the policy/policies or laws that the consultation informs. And the policy/laws that guide the consultation (if applicable).

**Comment by MaryBethBaker** [comment]
@jpmckinney and @biancawylie Thanks for the review of OpenConsult and giving your feedback about its use and limits. I need to look into how iCal and other calendar feeds deal with events that are months long or do not have a specific set period of time.

@biancawylie We're focused on the data that comes out of a consultation. I've done some work on a more overarching dataset. I hadn't thought about the use case you mention around Environmental consultations.

**Comment by neoinsight** [comment]
@jpmckinney On Feb 21, you said

> Consulting Canadians has a lot of consultations, many of which are for a narrow niche: http://www1.canada.ca/consultingcanadians/ A step-up from a basic feed would add some fields to help people filter the consultation opportunities.

Just to jump in here, there is already a set of filters for all of the consultation opportunities at Consulting with Canadians - to see it you have to click 'See all open opportunities' on the Consulting with Canadians landing page  -
 takes you to here: http://www1.canada.ca/consultingcanadians/page/search?lang=en&type=current&keywords=&year=0&departmentid=0&subjectid=0&start=1

The recommendations from the most recent usability research study in November 2016 had several tasks focused on that Consultation Finder (TBS R10). The recommendations, including how to find the filters more easily (!) were not implemented - not sure why.

**Comment by ThomKearney** [comment]
I think there are two standards in play. One for the consultation itself and another for the data generated. 

The consultation input is going to be pretty variable, but my thought was that if we (government) actually want to learn from everything we hear and not keep asking the same questions of people, then we need a way to mine results of previous consultations. It seems to me that there might be some common fields that would enable this, things like the source of the comment, the context, the specific question being answered, the general topic etc... as well as whatever categorization scheme was used in the analysis of the data. 

I cant help thinking that if we had open data for everything we are hearing from citizens and stakeholders that we would be creating a tremendous resource that would help us "know what we know".

**Comment by laurawesley** [comment]
#https://github.com/bcgov/openconsult/issues/6

**Comment by lisafast** [comment]
@laurawesley I did two rounds of research for Consulting with Canadians - second set of recommendations (Round 10 November 2016) were never implemented. Have shared R10 report with @RachelMuston via email - cannot share the results deck publicly as it has video links in it - participants gave government-only permission. 

Project sounds very fun!

**Comment by patcon** [comment]
Thanks Laura! Brought it to the attention of CivicTechTO community members [Merlin Chatwin](https://www.linkedin.com/in/merlin-chatwin-aa348219/) ([tweet](https://twitter.com/patconnolly/status/964291426778525697)) and [Jason Diceman](https://www.linkedin.com/in/jasondiceman/) ([tweet](https://twitter.com/patconnolly/status/964292576173019136)).

**Comment by MaryBethBaker** [comment]
Archiving this issue. Still waiting and excited about possible open standard for consultations data!
