### ISSUE TITLE
Public Engagement Resources

### ISSUE THREAD

**Issue by laurawesley** [canada-ca/welcome#3]
We have noticed that there are so many amazing resources online. What's your favorite and why? Provide links and credit where credit is due!

**Comment by RichardPietro** [comment]
As mentioned via Twitter, I created the [r/OpenGovCan](https://www.reddit.com/r/OpenGovCan/) subreddit to hopefully begin a conversation about Open Gov & Open Data :-)

I also now publish the ["Open Government Digest,"](http://ogtproductions.org/open-gov-digest) a twice-monthly snapshot of Open Government & Open Data news in Canada and abroad.

Thanks for starting this thread, Laura!

**Comment by chrismajewski** [comment]
Know your audience.  When I was at Earthquakes Canada twitter made sense for emergency reporting, it's where the politicians and reporters hung out.  We already had the responders sorted, our gap was information dissemination.

So... I hooked up our earthquake alert system to twitter:
https://twitter.com/canadaquakes
https://twitter.com/CANADAseisme

Rave reviews.

Who is your audience?  You can do better than "the general public"

**Comment by kentdaitken** [comment]
Involve UK's People and Participation guide: http://www.involve.org.uk//wp-content/uploads/2011/03/People-and-Participation.pdf

Why: great overview and provides easy-to-compare explanations of a pretty solid number of formats.

Dialogue by Design: A handbook in public and stakeholder engagement: http://www.mspguide.org/resource/dialogue-design-handbook-public-and-stakeholder-engagement

Why: assumes little but provides a guide to help would-be conveners think through needs, parameters, and stakeholders.

Bryson, Quick, Slotterback, Crosby's Designing Public Participation Processes: http://onlinelibrary.wiley.com/doi/10.1111/j.1540-6210.2012.02678.x/full

Why: research-backed overview of the state of the practice and the art of engagement design.

Rockefeller's Gather: The Art and Science of Effective Convening: https://www.rockefellerfoundation.org/report/gather-the-art-and-science-of-effective-convening/ (h/t @scilib)

Why: reading this gives you a solid sense of how much time, thought, and effort _should_ go into getting people together to think through issues.

**Comment by patcon** [comment]
[_Discuss. Decide. Do. The value of engagement as a decision support tool_](http://www.swerhun.com/our-book/) -- Nicole Swerhun and Vanessa AvRuskin, Swerhun Facilitation

Why: A small, concise book. Highly recommended by someone I trust who does public consultations at the municipal level. (I just started reading it.)

**Comment by kentdaitken** [comment]
+1 on the "trusting Bianca" front.

I have a couple copies of _Discuss. Decide. Do._ if anyone in Ottawa would like to borrow.

**Comment by kentdaitken** [comment]
This is a slight deviation but the best place to put it. Two articles that catalog policy analyst skills and what they spend time on, including external engagement. @laurawesley, is there anything available from the Digital Project in terms of digital skills gaps/inventories/training needs?

Policy Dialogue and Engagement between NonGovernmental Organizations and Government: A Survey of Processes and Instruments of Canadian Policy Workers:
http://www.cejpp.eu/index.php/ojs/article/viewFile/126/103

Policy capacity and incapacity in Canada's federal government: the intersection of policy analysis and street-level bureaucracy:
https://cfs.nrcan.gc.ca/publications?id=32598

We may revisit some of this research this year to give it a comparison over time and add other elements/questions.

**Comment by MaryBethBaker** [comment]
Archiving this thread.
