### ISSUE TITLE
Welcome to planning for our session at GovMaker 2016 // Bienvenue dans la planification de notre session à GovMaker 2016

### ISSUE THREAD

**Issue by RMarland** [canada-ca/welcome#5]
Welcome to planning for our session at GovMaker 2016 in Fredericton, November 21-22, on the theme of open dialogue and the role of [ public engagement principles](https://github.com/canada-ca/welcome/wiki/Draft-Guiding-Principles-for-Consultations-and-Public-Engagement) in practice. // Bienvenue dans la planification de notre session à GovMaker 2016, qui aura lieu à Fredericton les 21 et 22 novembre, autour du thème du dialogue ouvert et du rôle des [principes en matière de participation du public](https://github.com/canada-ca/welcome/wiki/Ebauche-des-principes-directeurs-des-consultations-et-de-la-participation-du-public) dans la pratique. 

**A question to kick us off…..** do you work with “principles” or “standards” for consultations or public engagement? Which ones?  

**Une question pour lancer la discussion…** Travaillez-vous avec des « principes » ou des « normes » pour les consultations ou la participation du public ? Lesquels ?

**Comment by ThomKearney** [comment]
Good questions to ask: 
https://twitter.com/thomkearney/status/793441569105928192

**Comment by laurawesley** [comment]
Hi everyone! If you're planning on joining us for [our session at GovMaker](http://www.govmakerconference.ca/timeline/), introduce yourself here and let us know what you'd like to get out of the workshop. :)

**Comment by patcon** [comment]
This issue might be good to close out now. But how'd the session go? Wish I could've made it. Feel free to drop or link any summaries in here for closure :)

**Comment by laurawesley** [comment]
Thanks @patcon - here's a quick summary of the session and the feedback, more to follow.

People appreciated the time to talk to each other - there was a lot of experience and positivity in the room. We got off to a late start and still had to finish on time - about 90 minutes. @mlevene from Open Gov team/TBS stayed with me and @RMarland went to Jaimie Boyd's workshop which was at the same time. @kentdaitken was also there as a participant, great continuity as he's worked on iterations of the principles and will also be travelling across Canada for his new job (maybe he can do the workshop in other cities?).

We had 50 participants including: a mayor, a city councillor, private sector entrepreneurs, civil society, fed, prov and municipal public servants from PEI, NS, NB and Ontario. It was nice to be in a minority as a federal public servant, to get out of my bubble for a while.

Started with a quick intro about who I was, asked about 6 people who they were, why were they there, then talked casually and slowly (not my MO!) for about 15 more minutes while I read the room (I was very tired from previous awesome but overwhelming day). 

Participants were at round tables about 6 per table. They had 30 minutes to discuss the principles. Most tables focused on one, so all of the principles got discussed by at least one group. It was enough time for people shared personal experiences, successes and challenges. We did not have time for the second part we had ready just in case (on barriers and enablers). Instead, we widened the conversation to the whole room with the reporting back of table discussions because there seemed to be some themes emerging and I wanted to see what would filter up and also enable more in-room connections.

We had 30 minutes to reporting back - about 10 or so people had a chance to share. We tried to [capture that feedback directly](https://twitter.com/richardpietro/status/801068834627190784) onto the [GitHub wiki page where the public engagement principles are listed](https://github.com/canada-ca/welcome/wiki/Draft-Guiding-Principles-for-Consultations-and-Public-Engagement). However, we had a little technical glitch so @mlevene took notes on a doc then we copied and pasted them after the session.

At the end of the plenary, participants challenged me to "show them what I heard by reflecting their feedback". I committed to ‎blogging about it on the [OpenGov blog](http://open.canada.ca/en/blog) and sent around the link to the [wiki page via Twitter](https://twitter.com/ResultsJunkie/status/801086819299422209).

We closed with a silent reflection‎ on the following 3 questions:
- What was the most important thing you heard?
- What was the most surprising thing you heard?
- What question do you still have?

Participants then filled in feedback forms and silently left the room. I waited outside collecting feedback forms and got about a dozen follow-up requests/ ideas - best practices to showcase,  offers to collaborate on research projects, etc. I also noticed some people used the other door to slip by me. ;)

## Summary of the Feedback
Here's a quick summary of the feedback. (Full disclosure: only about half the people filled in an evaluation form.)

**On the consultation principles:**
-Generally speaking, the 6 sets of principles resonated with people.
-Room for improvement on the language - a lot of people mentioned 'we' language seemed very government-centric
-Suggestion came up to use the principles as a guide to set expectations for each specific consultation, rather than general principles which could be seen as platitudes and defeat the purpose of having them at all.
-There wasn't much in the way of observable measures, what did come up was common questions. 
-Some people provided examples to follow (or not!) and that's what came up most as something that was missing from the session
-Redundancy was pointed out and words added, highlighted or crossed out.

**On the workshop format:**
-Overwhelmingly positive, though not everyone filled in evaluation form so I'm curious if the people who didn't like the format, or for whom the topic didn't resonate, didn't fill in the form.
I realized too late at least one table didn't have any feedback forms on it.
-People said the format embodied the principles and a desire and commitment of organizers to ‎listen, learn and collaborate.
-Suggested improvements included: case studies, more time, more content by the presenter.

**On the learning objectives:**
Lots of people said:
-They came to learn consultation framework: what works, how to do it, best practices
-What they actually learned was how much more complicated meaningful engagement is than they had thought‎.
-They still wanted to learn how to engage marginalized/disengaged/the unusual suspects.
-More people than I expected left their contact info and specific suggestions for follow-on - mostly offering stuff to us - like collaborating on a research framework. Those folks generally approached me in-person after as well.

**On the reflection:**
I was absolutely delighted that people left the sticky notes with the answers to the 3 questions...and that people stayed for this part. Themes definitely emerged even tho this part was silent:
-_Most important_: that government wants to meaningfully engage
-_Most surprising_: how hard it is to actually do so
-_Question remaining_: again, here a lot of variations on the theme of how to engage the disenfranchised / people who are not interested

**Comment by jpmckinney** [comment]
Earlier this year in March, the Canadian Open Dialogue Forum also workshopped open dialogue / public engagement principles. Did anyone have a look at them? https://docs.google.com/document/d/1IV-kJJs2RfvRyBQy4V8JdPNqyIun-_PQyuDDtalxJnA/edit

**Comment by kentdaitken** [comment]
@jpmckinney Yeah, the principles workshopped at CODF were an amalgam of Ontario's, a draft set of the Government of Canada's, and a few other sources. The GC's draft changed based on the CODF discussion, but (in my view) there was still work to do.

**Comment by jpmckinney** [comment]
@kentdaitken Having that document history written somewhere (e.g. in a footer or colophon) would be good, because right now the document just looks like it's reinventing the wheel. Adding that historical context would show how it builds on/is informed by related work.

**Comment by patcon** [comment]
@jpmckinney I just emailed Bryce, as per the doc intro, linking to your comment

**Comment by laurawesley** [comment]
Note has been added [on the wiki page](https://github.com/canada-ca/welcome/wiki/Draft-Guiding-Principles-for-Consultations-and-Public-Engagement) as per your suggestion @jpmckinney 

A few of the valuable insights that came out of the GovMaker workshop for me were:
1. The principles are too vague to be meaningful, but could be used to set expectations for each consultation - like a service pledge or commitment + service standards.
2. Many people are facing the same challenges (and hence, opportunities) regardless of level of government, so developing something openly that other governments could use, re-purpose or refine is worthwhile.
3. Principles in and of themselves aren't as useful as using those principles to uncover drivers of meaningful engagement. When we know what those drivers are, we could turn the principles into heuristics that could be used in the planning stages, or for meta-analysis on the outputs.

Sorry if this is bureaucratese; documenting as much for myself as for anyone that may find meaning or the reverse (debate).

**Comment by Studio1402** [comment]
Good morning! @RMarland and I are excited to be at GovMaker 2017 to talk about measuring meaningful engagement, based on the - now [published](http://open.canada.ca/en/content/principles-and-guidelines) - principles that the group explored last year. Looking forward to 'seeing you!

**Comment by MaryBethBaker** [comment]
Archiving this issue from event held in 2016.
